<?php


namespace App\Codes\Shipment;


use App\Codes\CodesInterface;

final class EcpayShipmentStatus implements CodesInterface
{
    const CODES = [
        300 => ['message' => '訂單處理中(已收到訂單資料)', 'description' => '訂單處理中'],
        310 => ['message' => '上傳電子訂單檔處理中', 'description' => '訂單處理中'],
        311 => ['message' => '上傳退貨電子訂單處理中', 'description' => '退貨訂單處理中'],
        325 => ['message' => '退貨訂單處理中(已收到訂單資料)', 'description' => '退貨訂單處理中'],
        2000 => ['message' => '出貨訂單修改', 'description' => '出貨訂單修改'],
        2001 => ['message' => '檔案傳送成功', 'description' => '訂單處理中'],
        2002 => ['message' => '出貨單號不合規則', 'description' => '配送異常，請和客服聯繫。'],
        2003 => ['message' => 'XML檔內出貨單號重複', 'description' => '配送異常，請和客服聯繫。'],
        2004 => ['message' => '出貨單號重複上傳使用(驗收時發現)', 'description' => '配送異常，請和客服聯繫。'],
        2005 => ['message' => '日期格式不符', 'description' => '配送異常，請和客服聯繫。'],
        2006 => ['message' => '訂單金額或代收金額錯誤', 'description' => '配送異常，請和客服聯繫。'],
        2007 => ['message' => '商品類型為空', 'description' => '配送異常，請和客服聯繫。'],
        2008 => ['message' => '訂單為空', 'description' => '配送異常，請和客服聯繫。'],
        2009 => ['message' => '門市店號為空', 'description' => '配送異常，請和客服聯繫。'],
        2010 => ['message' => '出貨日期為空', 'description' => '配送異常，請和客服聯繫。'],
        2011 => ['message' => '出貨金額為空', 'description' => '配送異常，請和客服聯繫。'],
        2012 => ['message' => '出貨編號不存在', 'description' => '配送異常，請和客服聯繫。'],
        2013 => ['message' => '母廠商不存在', 'description' => '配送異常，請和客服聯繫。'],
        2014 => ['message' => '子廠商不存在', 'description' => '配送異常，請和客服聯繫。'],
        2015 => ['message' => '出貨編號已存在(單筆)', 'description' => '配送異常，請和客服聯繫。'],
        2016 => ['message' => '門市已關轉店，將進行退貨處理', 'description' => '配送異常，請和客服聯繫。'],
        2017 => ['message' => '出貨日期不符合規定', 'description' => '配送異常，請和客服聯繫。'],
        2018 => ['message' => '服務類型不符規定(如只開取貨付款服務，確使用純取貨服務)', 'description' => '配送異常，請和客服聯繫。'],
        2019 => ['message' => '商品類型不符規定', 'description' => '配送異常，請和客服聯繫。'],
        2020 => ['message' => '廠商尚未申請店配服務', 'description' => '配送異常，請和客服聯繫。'],
        2021 => ['message' => '同一批次出貨編號重覆(批次)', 'description' => '配送異常，請和客服聯繫。'],
        2022 => ['message' => '出貨金額不符規定', 'description' => '配送異常，請和客服聯繫。'],
        2023 => ['message' => '取貨人姓名為空', 'description' => '配送異常，請和客服聯繫。'],
        2024 => ['message' => '物流作業驗收中', 'description' => '物流作業驗收中'],
        2025 => ['message' => '門市轉店號(舊門市店號已更新)', 'description' => '配送異常，請和客服聯繫。'],
        2026 => ['message' => '無此門市，將進行退貨處理', 'description' => '配送異常，請和客服聯繫。'],
        2027 => ['message' => '門市指定時間不配送(六、日)', 'description' => '配送異常，請和客服聯繫。'],
        2028 => ['message' => '門市關轉店，3日內未更新SUP(新店號)便至退貨流程', 'description' => '配送異常，請和客服聯繫。'],
        2029 => ['message' => '門市尚未開店', 'description' => '配送異常，請和客服聯繫。'],
        2030 => ['message' => '物流中心驗收成功', 'description' => '商品已送至物流中心'],
        2031 => ['message' => '未到貨(物流端未收到該商品)', 'description' => '配送異常，請和客服聯繫。'],
        2032 => ['message' => '商品瑕疵(進物流中心)', 'description' => '配送異常，請和客服聯繫。'],
        2033 => ['message' => '超材（註：統一超商及萊爾富物流使用）', 'description' => '配送異常，請和客服聯繫。'],
        2034 => ['message' => '違禁品(退貨及罰款處理)', 'description' => '配送異常，請和客服聯繫。'],
        2035 => ['message' => '訂單資料重覆上傳', 'description' => '配送異常，請和客服聯繫。'],
        2036 => ['message' => '已過門市進貨日（未於指定時間內寄至物流中心）', 'description' => '配送異常，請和客服聯繫。'],
        2037 => ['message' => '門市關轉(可使用SUP檔案更新原單號更新門市與出貨日)', 'description' => '配送異常，請和客服聯繫。'],
        2038 => ['message' => '第一段標籤規格錯誤', 'description' => '配送異常，請和客服聯繫。'],
        2039 => ['message' => '第一段標籤無法判讀', 'description' => '配送異常，請和客服聯繫。'],
        2040 => ['message' => '第一段標籤資料錯誤', 'description' => '配送異常，請和客服聯繫。'],
        2041 => ['message' => '物流中心理貨中', 'description' => '物流作業驗收中'],
        2042 => ['message' => '商品遺失', 'description' => '配送異常，請和客服聯繫。'],
        2043 => ['message' => '門市指定不配送(六、日)', 'description' => '配送異常，請和客服聯繫。'],
        2045 => ['message' => '不正常到貨(商品提早到物流中心)', 'description' => '配送異常，請和客服聯繫。'],
        2046 => ['message' => '貨件未取退回大智通物流中心', 'description' => '貨件未取退回大智通物流中心'],
        2047 => ['message' => '正常二退(退貨時間延長，在判賠期限內退回)', 'description' => '退貨'],
        2048 => ['message' => '商品瑕疵(商品在物流中心)', 'description' => '配送異常，請和客服聯繫。'],
        2049 => ['message' => '門市關店，將進行退貨處理', 'description' => '配送異常，請和客服聯繫。'],
        2050 => ['message' => '門市轉店，將進行退貨處理', 'description' => '配送異常，請和客服聯繫。'],
        2051 => ['message' => '廠商要求提早退貨（廠商出錯商品）', 'description' => '配送異常，請和客服聯繫。'],
        2052 => ['message' => '違禁品(退貨及罰款處理)', 'description' => '配送異常，請和客服聯繫。'],
        2053 => ['message' => '刷A給B', 'description' => '配送異常，請和客服聯繫。'],
        2054 => ['message' => '消費者要求提早拉退（消費者下訂單後又跟廠商取消）', 'description' => '配送異常，請和客服聯繫。'],
        2055 => ['message' => '更換門市', 'description' => '配送異常，請和客服聯繫。'],
        2057 => ['message' => '車輛故障，後續配送中', 'description' => '延遲配送中，請和客服聯繫。'],
        2058 => ['message' => '天候不佳，後續配送中', 'description' => '延遲配送中，請和客服聯繫。'],
        2059 => ['message' => '道路中斷，後續配送中', 'description' => '延遲配送中，請和客服聯繫。'],
        3012 => ['message' => '到所(收件人要求到站所取件)', 'description' => '到營業所取件'],
        3013 => ['message' => '當配下車(當日配送A至B營業所，已抵達B營業所)', 'description' => '當日配轉運中'],
        3014 => ['message' => '當配上車(當日配送從A至B營業所，已抵達A營業所)', 'description' => '當日配轉運中'],
        3015 => ['message' => '空運配送中', 'description' => '空運中'],
        3016 => ['message' => '配完狀態刪除', 'description' => null],
        3017 => ['message' => '退回狀態刪除(代收退貨刪除)', 'description' => null],
        3018 => ['message' => '到店尚未取貨，簡訊通知取件', 'description' => '到店尚未取貨'],
        3019 => ['message' => '退件到店尚未取貨，簡訊通知取件', 'description' => '退件到店尚未取貨'],
        3020 => ['message' => '貨件未取退回物流中心', 'description' => '貨件未取退回物流中心'],
        3021 => ['message' => '退貨商品未取退回物流中心', 'description' => '退貨商品未取退回物流中心'],
        3022 => ['message' => '買家已到店取貨', 'description' => '買家已到店取貨'],
        3023 => ['message' => '賣家已取買家未取貨', 'description' => '賣家已取買家未取貨'],
        3024 => ['message' => '貨件已至物流中心', 'description' => '貨件已至物流中心'],
        3025 => ['message' => '退貨已退回物流中心', 'description' => '退貨已退回物流中心'],
        3029 => ['message' => '商品已轉換店（商品送達指定更換之取件店舖）', 'description' => '到店尚未取貨(商品送達指定更換之取件店舖)'],
        3031 => ['message' => '退貨商品已轉換店（退貨商品送達指定更換之取件店舖）', 'description' => '退件到店尚未取貨'],
        3032 => ['message' => '賣家已到門市寄件', 'description' => '賣家已到門市寄件'],
        4001 => ['message' => '退貨商品已至門市交寄', 'description' => '退貨商品已至門市交寄'],
        4002 => ['message' => '退貨商品已至物流中心', 'description' => '退貨商品已至物流中心'],
        5001 => ['message' => '損壞，站所將協助退貨', 'description' => '調查處理中'],
        5002 => ['message' => '遺失', 'description' => '調查處理中'],
        5003 => ['message' => 'BASE列管', 'description' => '暫置轉運中心保管中（請聯絡黑貓宅急便）'],
        5004 => ['message' => '一般單退回', 'description' => '退貨'],
        5005 => ['message' => '代收退貨', 'description' => '客樂得貨物退回中'],
        5006 => ['message' => '代收毀損', 'description' => '調查處理中'],
        5007 => ['message' => '代收遺失', 'description' => '調查處理中'],
        5008 => ['message' => '退貨配完', 'description' => '退貨完成'],
        5009 => ['message' => '進貨門市發生緊急閉店，提早退貨至物流中心', 'description' => '配送作業異常'],
        7001 => ['message' => '超大(通常發生於司機取件，不取件)', 'description' => '調查處理中'],
        7002 => ['message' => '超重(通常發生於司機取件，不取件)', 'description' => '調查處理中'],
        7003 => ['message' => '地址錯誤，聯繫收件人', 'description' => '地址不明（調查處理中)'],
        7004 => ['message' => '航班延誤', 'description' => '航班延誤（調查處理中）'],
        7005 => ['message' => '託運單刪除', 'description' => null],
        7006 => ['message' => '小物流遺失', 'description' => '配送作業異常'],
        7007 => ['message' => '門市遺失', 'description' => '配送作業異常'],
        7008 => ['message' => '小物流破損，退回物流中心', 'description' => '配送作業異常'],
        7009 => ['message' => '商品包裝不良（物流中心反應）', 'description' => '配送作業異常'],
        7010 => ['message' => '商品包裝不良（門市反應）', 'description' => '配送作業異常'],
        7011 => ['message' => '取件門市閉店，轉退回原寄件店', 'description' => '取件門市閉店，請洽客服'],
        7012 => ['message' => '條碼重複或錯誤，物流中心客服處理', 'description' => '配送作業異常'],
        7013 => ['message' => '訂單超過驗收期限（商家未出貨）', 'description' => '訂單刪除'],
        7014 => ['message' => '商家未到貨（若訂單成立隔日未到貨即會發送，直到訂單失效刪除）', 'description' => null],
        7015 => ['message' => '條碼重複，物流中心客服處理', 'description' => '配送作業異常'],
        7016 => ['message' => '超材（註：全家物流使用）', 'description' => '配送異常，請和客服聯繫。'],
        9001 => ['message' => '退貨已取', 'description' => '退貨已取'],
        9002 => ['message' => '退貨已取', 'description' => '退貨已取'],
        9999 => ['message' => '訂單取消', 'description' => '訂單取消'],
        2068 => ['message' => '交貨便收件(A門市收到件寄件商品)', 'description' => '商品理貨中'],
        2069 => ['message' => '退貨便收件(商品退回指定C門市)', 'description' => '商品退回門市，請至門市領取'],
        2076 => ['message' => '消費者七天未取，商品退回至大智通', 'description' => '消費者七天未取，商品退回至大智通'],
        2077 => ['message' => '廠商未至門市取退貨，商品退回至大智通', 'description' => '廠商未至門市取退貨，商品退回至大智通'],
        2078 => ['message' => '買家未取貨退回物流中心-驗收成功', 'description' => '商品已送至物流中心'],
        2079 => ['message' => '買家未取貨退回物流中心-商品瑕疵(進物流中心)', 'description' => '配送異常，請和客服聯繫。'],
        2080 => ['message' => '買家未取貨退回物流中心-超材', 'description' => '配送異常，請和客服聯繫。'],
        2081 => ['message' => '買家未取貨退回物流中心-違禁品(退貨及罰款處理)', 'description' => '配送異常，請和客服聯繫。'],
        2082 => ['message' => '買家未取貨退回物流中心-訂單資料重覆上傳', 'description' => '配送異常，請和客服聯繫。'],
        2083 => ['message' => '買家未取貨退回物流中心-已過門市進貨日（未於指定時間內寄至物流中心）', 'description' => '配送異常，請和客服聯繫。'],
        2084 => ['message' => '買家未取貨退回物流中心-第一段標', 'description' => '配送異常，請和客服聯繫。'],
        2085 => ['message' => '買家未取貨退回物流中心-第一段標籤無法判讀', 'description' => '配送異常，請和客服聯繫。'],
        2086 => ['message' => '買家未取貨退回物流中心-第一段標籤資料錯誤', 'description' => '配送異常，請和客服聯繫。'],
        2087 => ['message' => '買家未取貨退回物流中心-物流中心理貨中', 'description' => '物流作業驗收中'],
        2088 => ['message' => '買家未取貨退回物流中心-商品遺失', 'description' => '配送異常，請和客服聯繫。'],
        2089 => ['message' => '買家未取退回物流中心-門市指定不配送(六、日)', 'description' => '配送異常，請和客服聯繫。'],
        2092 => ['message' => '買家未取退回物流中心-門市關轉', 'description' => '配送異常，請和客服聯繫。'],
        2093 => ['message' => '買家未取退回物流中心-爆量', 'description' => '配送異常，請和客服聯繫。'],
        2101 => ['message' => '門市關轉店', 'description' => '配送異常，請和客服聯繫。'],
        2102 => ['message' => '門市舊店號更新', 'description' => '配送異常，請和客服聯繫。'],
        2103 => ['message' => '無取件門市資料', 'description' => '配送異常，請和客服聯繫。'],
        2104 => ['message' => '門市臨時關轉店', 'description' => '配送異常，請和客服聯繫。'],
        3001 => ['message' => '轉運中(即集貨)', 'description' => '已集貨'],
        3002 => ['message' => '不在家', 'description' => '不在家，持續連絡配送'],
        3003 => ['message' => '配完', 'description' => '順利送達'],
        3004 => ['message' => '送錯BASE (送錯營業所)', 'description' => '調查處理中'],
        3005 => ['message' => '送錯CENTER(送錯轉運中心)', 'description' => '調查處理中'],
        3006 => ['message' => '配送中', 'description' => '配送中'],
        3007 => ['message' => '公司行號休息', 'description' => '公司行號休息，持續連絡配送'],
        3008 => ['message' => '地址不明，聯繫寄件人確認', 'description' => '地址不明(調查處理中)'],
        3009 => ['message' => '搬家', 'description' => '搬家(調查處理中)'],
        3010 => ['message' => '轉寄(如原本寄到A，改寄B)', 'description' => '轉寄配送中'],
        3011 => ['message' => '暫置營業所(收件人要求至營業所取貨)', 'description' => '暫置營業所保管中（請聯絡黑貓宅急便）'],
        3110 => ['message' => '轉配郵局', 'description' => '轉配郵局'],
        3111 => ['message' => '配送外包', 'description' => '配送外包'],
        3112 => ['message' => '再配', 'description' => '再次配送'],
        3113 => ['message' => '異常', 'description' => '配送異常，請和客服連繫。'],
        3114 => ['message' => '再取', 'description' => '再次取件']
    ];

    /**
     * @param int $code
     * @return array
     */
    static function getCode(int $code): array
    {
        return self::CODES[$code];
    }

    /**
     * @return array
     */
    static public function getCodes()
    {
        return self::CODES;
    }
}