name: Deploy

on: workflow_dispatch

jobs:
  deploy:
    name: 'Deployment'
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache for Composer
        uses: actions/cache@v2
        id: cache-test
        with:
          path: vendor
          key: v0-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: exif, gd, intl, pcntl, zip
          tools: deployer/deployer:~7.0@dev

      - name: Prepare SSH Key for Deployer
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOYER_SSH_KEY" > ~/.ssh/id_deployer
          echo "$DEPLOYER_SSH_PUBLIC_KEY" > ~/.ssh/id_deployer.pub
          chmod 600 ~/.ssh/id_deployer
          SSH_CONFIG="Host snsgal.com.tw\n\tHostName $SSH_HOST\n\tUser deployer\n\tIdentityFile ~/.ssh/id_deployer\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile /dev/null\n"
          echo -e "$SSH_CONFIG" >> ~/.ssh/config
        env:
          DEPLOYER_SSH_KEY: ${{ secrets.DEPLOYER_SSH_KEY }}
          DEPLOYER_SSH_PUBLIC_KEY: ${{ secrets.DEPLOYER_PUBLIC_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_SERVER_KEY: ${{ secrets.SSH_SERVER_KEY }}

      - name: Prepare Hosts Fingerprints
        run:
          echo "$SSH_HOST ssh-rsa $SSH_SERVER_KEY" >> ~/.ssh/known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_SERVER_KEY: ${{ secrets.SSH_SERVER_KEY }}

      - name: Ensure Directory Permissions
        run: sudo chmod -R 777 storage bootstrap/cache

      - name: Prune Git Repositories
        run: |
          git show-ref -s "$GITHUB_REF" > .git/shallow
          git reflog expire --expire=0
          git prune
          git prune-packed

      - name: Install NPM Dependencies
        uses: bahmutov/npm-install@v1

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist --no-dev --ignore-platform-reqs

      - name: Deploy
        run: dep deploy production
